---
# ansible.web_stack/tasks/main.yml
- import_tasks: include-vars.yml
  tags: ['web_stack']

# http installation
- import_tasks: httpd.yml
  tags: ['web_stack','web_stack.httpd']

# php installation
- import_tasks: php.yml
  tags: ['web_stack','web_stack.php']


# letsencrypt installation
- import_tasks: letsencrypt.yml
  tags: ['web_stack','web_stack.letsencrypt']





...
